services:
  orders-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=orders
    ports:
      - "5432:5432"
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  orders-db-data: