name: orders

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=orders
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - APP_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=orders
      - DB_PASSWORD=123456
      - DB_SSLMODE=disable
      - DB_MAX_CONNS=20
      - DB_MIN_CONNS=2
      - DB_MAX_CONN_LIFETIME=30m
      - MIGRATIONS_PATH=/app/migrations
    restart: unless-stopped

volumes:
  postgres-data: