services:
  orders-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=orders
    ports:
      - "5432:5432"
    volumes:
      - orders-db-data:/var/lib/postgresql/data
    restart: unless-stopped
  user-service:
    image: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=ecommerce
      - DB_PASS=postgres
      - DB_SSLMODE=disable